version: '3.9'

services:
  telegram-bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=order_119
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - connection

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: order_119
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - connection


networks:
  connection:
    driver: bridge

volumes:
  postgres_data: